# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-05 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191005_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='section',
        ),
        migrations.AddField(
            model_name='lab',
            name='slot',
            field=models.CharField(default='1', max_length=10, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lab',
            name='subject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
            preserve_default=False,
        ),
    ]
