# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-05 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191005_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lab',
            field=models.BooleanField(default=False),
        ),
    ]
