# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-05 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attendance_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lab',
            name='subslot',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lab',
            name='slot',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='lab',
            unique_together=set([('slot', 'subslot')]),
        ),
    ]
