# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-05 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_timetable_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='category',
            field=models.CharField(choices=[('lab', 'lab'), ('section', 'section')], default='section', max_length=20),
        ),
    ]
