# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-12 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191006_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
