# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-02 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Student'),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Teacher'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
