# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-02 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191002_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Teacher'),
        ),
    ]
